# Change these first
owner: novacSavvyy # Your GitHub organization or username, where this repository lives
repo: simpliiUptime # The name of this repository

sites:
  - name: Simplii Dev
    url: http://dev.admin-web-simplii.savvyy.io/
  - name: Simplii Release
    url: http://release.admin-web-simplii.savvyy.io/
  - name: Simplii Alpha
    url: http://alpha.admin-web-simplii.savvyy.io/
  - name: Simplii Beta
    url: http://beta.admin-web-simplii.savvyy.io/
  - name: Simplii Gamma
    url: http://gamma.admin-web-simplii.savvyy.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /simpliiUptime
  logoUrl: https://dev.admin-web-simplii.savvyy.io/assets/brands/simplii/logo/dark/Simplii_Primary_Logo_rgb.png
  name: Simplii SAVVYY Uptime
  introTitle: "**SAVVYY** is a next-gen digital lending platform"
  introMessage: This page will show you the status of our various environments and their uptime!
  navbar:
    - title: Savvyy
      href: https://savvyy.ai

i18n:
  footer: Contact us at [support@savvyy.ai](mailto:support@savvyy.ai)
